name: Build and Test

on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  build-and-test-standard-runners:
    name: Build and Test
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@dev
    with:
      timeout-minutes: 20
